// This file is auto-generated by `ember build`.
// You should not modify it.

require('./vendor/jquery');
require('./vendor/handlebars');
require('./vendor/ember');
require('./vendor/ember-data');
require('./templates');


var App = window.App = require('./app');

App.Store = require('./store');

App.EditFilterController = require('./controllers/edit_filter_controller');
App.FilterController = require('./controllers/filter_controller');
App.NewFilterController = require('./controllers/new_filter_controller');
App.Filter = require('./models/filter');
App.FiltersRoute = require('./routes/filters_route');
App.NewFilterRoute = require('./routes/new_filter_route');

require('./routes');

